### PR TITLE
refactor: add creation time field for comments and replies

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

增加迁移时评论和回复的创建时间字段。适配：https://github.com/halo-dev/halo/pull/3341

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/3330

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by LIlGG** [comment]
> 由于当前 PR 适配了 [halo-dev/halo#3341](https://github.com/halo-dev/halo/pull/3341)，是否需要修改插件定义的 requires 字段来限制只允许在 2.3.0 及以上的版本运行？

确实应该限制，已进行补充。

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
